export const PRODUCT_TAGS = [
    'CPU',
    'RAM',
    'Ổ cứng',
    'Card đồ họa ',
    'Màng hình',
    'Cỗng giao tiếp',
    'Âm thanh',
    'Bàn phím',
    'Chuẩn LAN',
    'Chuẩn WIFI',
    'Bluetooth',
    'Webcam',
    'Hệ điều hành',
    'Pin',
    'Trọng lượng',
    'Màu sắc',
    'Kích thước',
];
