const routes = {
    home: '/',
    store: 'product',
    introduce: 'introduce',
    contact: '/contact',
    product_detail: 'product/:id',
    register: '/register',
    login: '/login',
    forgot_pw: '/forget-password',
    user: 'user',
    order: 'order',
    userDetail: 'profile',
    changePassword: 'changepassword',
    history: 'history',
    cartDetail: 'cart',
    _404: '*',
    // following: '/following',
    // profile: '/@:nickname',
    // upload: '/upload',
    // newMusic: '/newmusic',
    // category: '/category',
    // top: '/top10',
};

export default routes;
