const routes = {
    home: '/',
    store: 'product',
    product_detail: 'product/:id',
    register: '/register',
    login: '/login',
    forgot_pw: '/forget-password',
    user: 'user',
    order: 'order',
    notify: 'notify',
    userDetail: 'profile',
    changePassword: 'changepassword',
    history: 'history',
    cartDetail: 'cart',
    _404: '*',
    adminPage: '/admin',
    dashboard: 'dashboard',
    account: 'account',
    accountDetail: 'account/account-detail',
    addAccount: 'account/add-account',
    adminProducts: 'products',
    addProduct: 'products/add-product',
    updateProduct: 'products/update-product/:id',
    adminOrders: 'order',
    adminOrderDetail: 'order/order-detail',
    adminNotify: 'notify',
    addNotify: 'notify/add-notify',
    memberProfile: 'member-profile',
    Advertising: 'advertising',
    Brand: 'brand',
    Category: 'category-series',
};

export default routes;
